[package]
name = "yajl-ffi-test-suite"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
publish = false

[lib]
doc = false
doctest = false

[[test]]
name = "yajl-ffi-test-suite"
path = "tests/api/yajl_ffi_test_suite.rs"

[dependencies]
yajl-clib = { workspace = true }
libc = { workspace = true }

[features]
default = []
nightly = []

[dev-dependencies]
insta = { version = "1.41.1", features = ["yaml"] }
rstest = "0.23.0"
