[package]
name = "yajl"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
path = "src/yajl.rs"

[[test]]
name = "yajl-api-tests"
path = "tests/api/yajl_api_tests.rs"

[features]
default = []

nightly = []

[dependencies]
libc = { workspace = true }
strtod = { git = "https://github.com/kod-kristoff/strtod" }


[dev-dependencies]
anyhow = "1.0.92"
insta = { version = "1.41.1", features = ["yaml"] }
rstest = "0.23.0"
